services:
  redis:
    image: redis:7-alpine
    container_name: hr-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr-backend
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:changeme@host.docker.internal:5432/hr?sslmode=disable}
      PORT: 3041
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH: ${JWT_REFRESH}
      REDIS_URL: redis://:${REDIS_PASSWORD:-changeme}@redis:6379
      ZK_IP: ${ZK_IP:-192.128.69.33}
      ZK_PORT: ${ZK_PORT:-4370}
      TZ: Asia/Jakarta
    ports:
      - "3041:3041"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL_PRODUCTION: ${API_URL}
    container_name: hr-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3040:3000"
